# Generated by Django 5.0 on 2024-04-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Campus_id', models.CharField(max_length=255)),
                ('Name', models.TextField(blank=True, null=True)),
                ('Age', models.IntegerField()),
                ('Gender', models.TextField(blank=True, null=True)),
                ('Address', models.TextField(blank=True, null=True)),
                ('PUC_Background', models.TextField(blank=True, null=True)),
                ('PUC_Marks', models.IntegerField(blank=True, null=True)),
                ('Batch', models.IntegerField()),
                ('Course', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
